"""Common task-first contracts and id helpers."""

from mobiflow_agent.common.contracts import (
    ApprovalMode,
    EntityKind,
    EvidenceKind,
    EvidenceRef,
    ExecutionProposal,
    ObservationFact,
    ObservationFactSource,
    ObservationInference,
    ObservationView,
    StrictModel,
    SuccessCriterion,
    TaskConstraint,
    TaskContract,
    VerificationCheck,
    VerificationSpec,
    VerificationStatus,
    VerificationVerdict,
)
from mobiflow_agent.common.ids import (
    build_role_request_id,
    build_role_result_id,
    build_task_contract_id,
    build_task_plan_id,
    build_task_session_id,
    build_task_step_id,
)

__all__ = [
    "ApprovalMode",
    "EntityKind",
    "EvidenceKind",
    "EvidenceRef",
    "ExecutionProposal",
    "ObservationFact",
    "ObservationFactSource",
    "ObservationInference",
    "ObservationView",
    "StrictModel",
    "SuccessCriterion",
    "TaskConstraint",
    "TaskContract",
    "VerificationCheck",
    "VerificationSpec",
    "VerificationStatus",
    "VerificationVerdict",
    "build_role_request_id",
    "build_role_result_id",
    "build_task_contract_id",
    "build_task_plan_id",
    "build_task_session_id",
    "build_task_step_id",
]
